# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8b8123eeb6835b7d132052742b8b3338f120a9282683cf2c63ed6eacc555ba7fde463c1be3ee67e8191bd1e63ded1798f17fa649e7f51e8e647165d2a07e652

test:
  secret_key_base: 5dde1b1fcb5eb44ae6dd24229fd0de1cc7faca8f3fe22d854de0115f249a662e9725a987230a358a0d9a968d0d037395ec94e374c3559ca260815c40441faa9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
